resources:
- name: ${namespace}-repository
  type: git
  source:
    uri: ${source_code_url}.git
    branch: ${branch}
- name: gitops-repository
  type: git
  source:
    uri: https://github.com/ministryofjustice/cloud-platform-terraform-gitops
    branch: master
- name: tools-image
  type: docker-image
  source:
    repository: ministryofjustice/cloud-platform-tools
    tag: concourse

groups: 
- name: deploy
  jobs: [deploy-application]

jobs:

- name: deploy-application
  serial: true
  plan:
    - in_parallel:
      - get: ${namespace}-repository
        trigger: true
      - get: gitops-repository
        trigger: true
      - get: tools-image
    - task: ${namespace}
      image: tools-image
      config:
        platform: linux
        inputs:
          - name: ${namespace}-repository
        params:
          KUBECONFIG: "/tmp/kubconfig"
          KUBESECRET: ((kubectl-conf.kubeconfig))
        run:
          path: /bin/bash
          dir: ${namespace}-repository
          args:
            - -c
            - |
              printf "%s" "$${KUBESECRET}" >"$${KUBECONFIG}"
              kubectl --kubeconfig "$${KUBECONFIG}" -n concourse-${github_team} get secret ${github_team}-gpg-seckey -ojson | jq -r '.data.key | @base64d' | gpg --batch --import
              git-crypt unlock
              kubectl --kubeconfig "$${KUBECONFIG}" -n ${namespace} apply -f ./cloud-platform-deploy/${namespace}/. --as "system:serviceaccount:concourse-${github_team}:deploy"

