resources:
- name: ${namespace}-repository
  type: git
  source:
    uri: ${source_code_url}.git
    branch: ${branch}
- name: tools-image
  type: docker-image
  source:
    repository: ministryofjustice/cloud-platform-tools
    tag: concourse

groups: 
- name: deploy
  jobs: [deploy-application]

jobs:

- name: deploy-application
  serial: true
  plan:
    - in_parallel:
      - get: ${namespace}-repository
        trigger: true
      - get: tools-image
    - task: ${namespace}
      image: tools-image
      config:
        platform: linux
        inputs:
          - name: ${namespace}-repository
        params:
          AWS_ACCESS_KEY_ID: ((aws-live-1.access-key-id))
          AWS_SECRET_ACCESS_KEY: ((aws-live-1.secret-access-key))
          KUBECONFIG: /tmp/kubeconfig
        run:
          path: /bin/bash
          dir: ${namespace}-repository
          args:
            - -c
            - |
              (
                AWS_ACCESS_KEY_ID="$${AWS_ACCESS_KEY_ID}"
                AWS_SECRET_ACCESS_KEY="$${AWS_SECRET_ACCESS_KEY}"
                aws s3 cp s3://cloud-platform-concourse-kubeconfig/concourse-config /tmp/kubeconfig
              )
              kubectl -n ${namespace} apply -f ./cloud-platform-deploy/helloworld-dev/. --as "system:serviceaccount:${namespace}:deploy"
