resources:
- name: helloworld-repository
  type: git
  source:
    uri: https://github.com/ministryofjustice/cloud-platform-helloworld-ruby-app
    branch: add/gitops
- name: tools-image
  type: docker-image
  source:
    repository: registry.hub.docker.com/ministryofjustice/cloud-platform-smoke-tests
    tag: 1.3

groups: 
- name: applicaton
  jobs: [apply-application]

jobs:
- name: apply-application
  serial: true
  plan:
    - aggregate:
      - get: helloworld-repository
        trigger: true
      - get: tools-image
        trigger: false
    - task:
      image: tools-image
      config:
        platform: linux
        inputs:
          - name: helloworld-repository
        run:
          path: /bin/sh
          
