resources:
- name: helloworld-repository
  type: git
  source:
    uri: https://github.com/ministryofjustice/cloud-platform-helloworld-ruby-app.git
    branch: add/gitops
- name: tools-image
  type: docker-image
  source:
    repository: ministryofjustice/cloud-platform-tools
    tag: concourse

groups: 
- name: deploy
  jobs: [deploy-application]

jobs:

- name: deploy-application
  serial: true
  plan:
    - aggregate:
      - get: helloworld-repository
        trigger: true
      - get: tools-image
    - task: helloworld
      image: tools-image
      config:
        platform: linux
        inputs:
          - name: helloworld-repository
        params:
          AWS_ACCESS_KEY_ID: ((aws-concourse-op.access-key-id))
          AWS_SECRET_ACCESS_KEY: ((aws-concourse-op.secret-access-key))
          KUBECONFIG: /tmp/kubeconfig
        run:
          path: /bin/bash
          dir: helloworld-repository
          args:
            - -c
            - |
              (
                AWS_ACCESS_KEY_ID="${AWS_ACCESS_KEY_ID}"
                AWS_SECRET_ACCESS_KEY="${AWS_SECRET_ACCESS_KEY}"
                aws s3 cp s3://cloud-platform-concourse-kubeconfig/concourse-config /tmp/kubeconfig
              )
              kubectl -n helloworld-dev apply -f ./cloud-platform-deploy/helloworld-dev/. --as "system:serviceaccount:helloworld-dev:deploy"
