resources:
- name: helloworld-repository
  type: git
  source:
    uri: https://github.com/ministryofjustice/cloud-platform-helloworld-ruby-app
    branch: add/gitops
- name: tools-image
  type: docker-image
  source:
    repository: ministryofjustice/cloud-platform-tools
    tag: concourse

groups: 
- name: deploy
  jobs: [deploy-application]

jobs:
- name: deploy-application
  serial: true
  plan:
    - aggregate:
      - get: helloworld-repository
        trigger: true
      - get: tools-image
        trigger: false
    - task:
      image: tools-image
      config:
        platform: linux
        inputs:
          - name: helloworld-repository
        run:
          path: /bin/sh
            KUBECONFIG_AWS_ACCESS_KEY_ID: ((aws-concourse-op.access-key-id))
            KUBECONFIG_AWS_SECRET_ACCESS_KEY: ((aws-concourse-op.secret-access-key))
            KUBECONFIG: /tmp/kubeconfig
            # the variables prefixed with PIPELINE_ are used by the apply script
            TF_VAR_concourse_basic_auth_username: ((concourse-basic-auth.username))
            TF_VAR_concourse_basic_auth_password: ((concourse-basic-auth.password))
          run:
            path: /bin/sh
            dir: cloud-platform-environments-repo
            args:
              - -c
              - |
                (
                  AWS_ACCESS_KEY_ID="${KUBECONFIG_AWS_ACCESS_KEY_ID}"
                  AWS_SECRET_ACCESS_KEY="${KUBECONFIG_AWS_SECRET_ACCESS_KEY}"
                  aws s3 cp s3://cloud-platform-concourse-kubeconfig/concourse-config /tmp/kubeconfig
                )
                kubectl apply -f ./cloud-platform-deploy/helloworld-dev/. -n helloworld-dev --as "system:serviceaccount:helloworld-dev:deploy" 
