jobs:
- name: cronjobber
  plan:
  - get: tools-image
  - config:
      container_limits: {}
      outputs:
      - name: files
      params:
        RELEASE: 0.2.0
      platform: linux
      run:
        args:
        - -exc
        - |
          wget -q https://github.com/hiddeco/cronjobber/archive/${RELEASE}.tar.gz
          tar xzf ${RELEASE}.tar.gz --strip-components=1
        dir: files
        path: /bin/bash
    image: tools-image
    task: download
resources:
- name: tools-image
  source:
    repository: ministryofjustice/cloud-platform-tools
    tag: 1.3
  type: docker-image
